[package]
name = "static_site_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.9"
actix-web = "4.12.1"
pulldown-cmark = "0.13.0"
serde = "1.0.228"
serde_json = "1.0.148"
toml = "0.9.10"
